# Introduction to NumPy

NumPy (Numerical Python) is a powerful Python library for numerical computing. It provides:
- Multidimensional arrays (ndarrays)
- Mathematical functions to operate on arrays
- Tools for linear algebra, Fourier transforms, and random number generation

Resources:

- https://numpy.org/doc/stable/user/quickstart.html
- https://numpy.org/doc/stable/user/absolute_beginners.html

In [1]:
# Importing numpy
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.2.6


## Creating Arrays

We can create arrays from Python lists or using built-in NumPy functions.

In [2]:
# Creating a NumPy array from a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)
print("Type:", type(arr1))
print("Shape:", arr1.shape)

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)


In [3]:
# Creating arrays with built-in functions
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
arange_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Arange:\n", arange_arr)
print("Linspace:\n", linspace_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]


## Array Operations

NumPy allows element-wise operations and broadcasting.

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Scalar multiplication:", a * 2)
print("Dot product:", np.dot(a, b))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar multiplication: [2 4 6]
Dot product: 32


## Indexing and Slicing

We can access elements and slices of arrays, similar to Python lists.

In [5]:
arr = np.arange(10)
print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [2:7]:", arr[2:7])
print("Step slice [::2]:", arr[::2])

Array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Last element: 9
Slice [2:7]: [2 3 4 5 6]
Step slice [::2]: [0 2 4 6 8]


## Reshaping Arrays

NumPy allows reshaping arrays without copying data.

In [6]:
matrix = np.arange(1, 13)
reshaped = matrix.reshape((3, 4))
print("Original:", matrix)
print("Reshaped:\n", reshaped)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Useful Functions

Some common mathematical functions:

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Sum: 15
Mean: 3.0
Standard deviation: 1.4142135623730951
Max: 5
Min: 1


## Random Numbers

NumPy provides functionality for generating random numbers.

In [8]:
rand_arr = np.random.rand(3, 3)
rand_ints = np.random.randint(0, 10, (3, 3))

print("Random floats:\n", rand_arr)
print("Random integers:\n", rand_ints)

Random floats:
 [[0.52921123 0.98176815 0.94562919]
 [0.20991028 0.12195987 0.13613847]
 [0.81434196 0.33440791 0.99887439]]
Random integers:
 [[4 6 3]
 [8 6 5]
 [5 6 8]]
